deployment_account          = "medly-test"
aws_region                  = "us-east-1"
env                         = "test"
domain_name                 = "test-medly.io"
availability_zones          = ["us-east-1a", "us-east-1b"]
cidr_block                  = "10.111.0.0/16"
private_subnets             = ["10.111.0.0/24", "10.111.1.0/24"]
public_subnets              = ["10.111.2.0/24", "10.111.3.0/24"]
database_subnets            = ["10.111.4.0/24", "10.111.5.0/24"]
rds_username                = "scheduling_service_user"
rds_password                = "scheduling_service_password"
rds_dbname                  = "scheduling_service_db"
rds_max_capacity            = 2
rds_min_capacity            = 2
rds_auto_pause              = false
bastion_aws_key_pair_name   = "scheduling_service_bastion"
api_gateway_types           = ["REGIONAL"]
service_name                = "scheduling-service"
enable_rds_secrets_rotation = true
enable_http_endpoint        = true
allow_rds_secret_access     = true
enable_api_gw_logging       = false
api_gw_logging_level        = "INFO"
