aws_region         = "us-east-1"
env                = "test"
aws_profile        = "medly-test"
lambda_account_arn = "arn:aws:iam::592280881349:role/deployment-dev-us-east-1-lambdaRole"
service_name       = "deployment"
