aws_region            = "us-east-1"
domain_name           = "medly.io"
cname                 = "providers-gw"
cloudfront_log_bucket = "medly-prod-logs.s3.amazonaws.com"
cloudfront_log_prefix = "cloudfront-providers-gw-proxy-logs"
