aws_profile                   = "medly-prod"
aws_region                    = "us-east-1"
deployment_account            = "medly-prod"
env                           = "prod"
service_name                  = "satellite-service"
availability_zones            = ["us-east-1d", "us-east-1c"]
cidr_block                    = "10.158.0.0/16"
private_subnets               = ["10.158.0.0/24", "10.158.1.0/24"]
public_subnets                = ["10.158.2.0/24", "10.158.3.0/24"]
database_subnets              = ["10.158.4.0/24", "10.158.5.0/24"]
api_gateway_types             = ["REGIONAL"]
provisioned_concurrency_count = 5
enable_api_gw_logging         = true
api_gw_logging_level          = "INFO"
