aws_region                            = "us-east-1"
env                                   = "uat"
aws_profile                           = "medly-uat"
sync_stream_lambda_execution_role_arn = "arn:aws:iam::164055005537:role/kinesisStream-prod-us-east-1-lambdaRole"
service_name                          = "stream-sync"
