aws_profile             = "medly-sandbox"
aws_region              = "us-east-1"
deployment_account      = "medly-sandbox"
service_name            = "ibd"
env                     = "sandbox"
availability_zones      = ["us-east-1a", "us-east-1b"]
domain_name             = "sandbox-medly.io"
cidr_block              = "10.1.0.0/16"
private_subnets         = ["10.1.0.0/24", "10.1.1.0/24"]
public_subnets          = ["10.1.2.0/24", "10.1.3.0/24"]
database_subnets        = ["10.1.4.0/24", "10.1.5.0/24"]
rds_username            = "ibd_user"
rds_password            = "ibd_password"
rds_dbname              = "ibd_db"
rds_max_capacity        = 2
rds_min_capacity        = 2
rds_auto_pause          = false
amplify_repository_url  = "https://github.com/medlypharmacy/ibd-app"
amplify_github_enabled  = true
amplify_branch_patterns = "master, ibd-*, IBD-*"