module "primerx_ingest" {
  source                       = "../../../modules/services/primerx_ingest"
  env                          = var.env
  aws_region                   = var.aws_region
  pr_vpc_cidr_block            = var.pr_vpc_cidr_block
  pr_private_subnets           = var.pr_private_subnets
  pr_public_subnets            = var.pr_public_subnets
  pr_availability_zones        = var.pr_availability_zones
  pr_ami_id                    = var.pr_ami_id
  pr_instance_type             = var.pr_instance_type
  pr_key_name                  = var.pr_key_name
  pr_allowed_cidr_blocks       = var.pr_allowed_cidr_blocks
  pr_db_allowed_cidr_blocks    = var.pr_db_allowed_cidr_blocks
  db_allowed_security_groups   = [module.primerx_ingest.security_group_id]
  mmspy_eb_app_name            = var.mmspy_eb_app_name
  mmspy_solution_stack_name    = var.mmspy_solution_stack_name
  mmspy_environment_type       = var.mmspy_environment_type
  mmspy_aws_key_pair_name      = var.mmspy_aws_key_pair_name
  mmspy_tier                   = var.mmspy_tier
  mmspy_instance_type          = var.mmspy_instance_type
  mmspy_environment_variables  = var.mmspy_environment_variables
  ebp_version                  = var.ebp_version
  ebp_name                     = var.ebp_name
  ebp_ecr_image_tag_mutability = var.ebp_ecr_image_tag_mutability
}
