aws_region            = "us-east-1"
domain_name           = "medly.io"
subdomain_internal    = "api-gw"
subdomain_partners    = "api"
cloudfront_log_bucket = "medly-prod-logs.s3.amazonaws.com"
cloudfront_log_prefix = "cloudfront-proxy-logs"
