service_name = "atlantis-eb"
env          = "medly-dev"
account_id   = "592280881349"
aws_region   = "us-east-1"
tags = {
  Name = "atlantis-eb"
}
vpc_cidr_block        = "10.4.0.0/16"
private_subnets       = ["10.4.1.0/24"]
public_subnets        = ["10.4.2.0/24"]
availability_zones    = ["us-east-1a", "us-east-1b"]
enable_dns_support    = "true"
enable_dns_hostnames  = "true"
enable_nat_gateway    = "false"
app_name              = "eb-atlantis"
solution_stack_name   = "64bit Amazon Linux 2 v3.0.3 running Go 1"
environment_type      = "SingleInstance"
aws_key_pair_name     = "eb-atlantis"
tier                  = "WebServer"
environment_variables = {}
instance_type         = "t3.medium"