name: linter
on:
  push:
    branches: [ main ]
  pull_request:
    

jobs:
  tflint:
    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v1
      name: Checkout source code

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.5

    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint
      with:
        tflint_version: v0.26.0

    - name: Run TFLint
      run: tflint -f compact

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -list=true -write=false -diff=true -check=true -recursive
      continue-on-error: false